certs.yaml

Also it does not disable the event if the domain uses it's own ssl certificate.

Disable event for *.gyaanipedia.co.in apart from where the domain is en.gyaanipedia.co.in

---

redirects.yaml

Change redirect

---

redirects.yaml

Add redirect for tallguysfree wiki

---

certs.yaml
redirects.yaml

Redirect mobile domains to the real domain.

Remove mobile domains

---

redirects.yaml

Domain does not work (e.g ssl errors).

Remove wiki.m.iufs.jp

---

certs.yaml

Remove wiki.archman.de

---

redirects.yaml

redirect: +1 for mcuwiki

---

redirects.yaml

At least I know the cert revoked right

Update ssl certs for .mh.o redirects

---

redirects.yaml

Link:  https://meta.miraheze.org/w/index.php?title=User_talk:Reception123&oldid=168212#Redirect_issue

Per request

---

redirects.yaml

We're migrating from using mobile domain to proper names and to have actual support for regex domains within

Add new regex configs to orain

---

certs.yaml

domain no longer pointing at us.

Remove chouverse.cludisciples.cyou

---

redirects.yaml

ats is no longer being tested and was removed

Remove regex_domain_ats

---

certs.yaml

Not 100% sure I did this right but I think it'll work.

Setup betaheze.org as a wildcard ssl

---

redirects.yaml

Adds redirects for squareenixwiki and polandballwiki. First one requested by ResultsMayVary on #miraheze-offtopic and second one requested by me.

Add redirects 

---

redirects.yaml

Requested on #miraheze-offtopic by wiki bureaucrat

Redirect mario.* to custom domain

---

redirects.yaml

T9129: Potential fix

---

redirects.yaml

ps: I'm not sure if `additional_domains` is fine in case I would add another domain to be aliased in the future.

Add redirects for wiki.rtapp.tk and wiki.recaptime.tk as per T9210

---

redirects.yaml

Revert "Unset redirect for polandballwiki.com"

---

certs.yaml
redirects.yaml

Per https://phabricator.miraheze.org/T11080

Redirect wikiyri.org to en.wikiyri.org

---

redirects.yaml

Redirect tintinpedia.miraheze.org to tintinpedia.fr

---

certs.yaml

https://meta.miraheze.org/wiki/Special:RequestSSLQueue/182

Add wiki.graalmilitary.com

---

redirects.yaml

https://issue-tracker.miraheze.org/T13264
Fixes T13264

T13264: Redirect capoeirawiki to capoeirawiki.org

---

certs.yaml

T13351: Use Cloudflare certificate for burnout.wiki

---

redirects.yaml

https://issue-tracker.miraheze.org/T13627

Redirect chinafake wiki (T13627)

---

certs.yaml

https://meta.miraheze.org/wiki/Special:RequestSSLQueue/518

certs: Add exodusgame.wiki

---

redirects.yaml

T13492: Redirect three wikis to their custom domain

---

redirects.yaml

https://issue-tracker.miraheze.org/T13770

T13770: Redirect everythingupgradetreewiki

---

redirects.yaml

https://issue-tracker.miraheze.org/T13818

T13818: Redirect digwiki

---

redirects.yaml

Addresses [T13809](https://issue-tracker.miraheze.org/T13809) and [T13689](https://issue-tracker.miraheze.org/T13689)

Redirects for citywikiwiki and bunkshelfwiki

---

redirects.yaml

Addresses [T13829](https://issue-tracker.miraheze.org/T13829).

T13829: Redirect fischwiki

---

redirects.yaml

T13791: Redirect www.wikimoma.art to wikimoma.art

---

redirects.yaml

Resolves [T13885](https://issue-tracker.miraheze.org/T13885).

T13885: Redirect otherkin.miraheze.org to otherkin.wiki

---

redirects.yaml

Resolves [T13892](https://issue-tracker.miraheze.org/T13892).

T13892: Redirect handhelds.miraheze.org to handhelds.wiki

---

redirects.yaml

Resolves [T13951](https://issue-tracker.miraheze.org/T13951).

T13951: Redirect cytus2.miraheze.org to c2wiki.starsky919.xyz

---

redirects.yaml

Requested on [Discord](https://discord.com/channels/407504499280707585/1391551820580524033/1391552758720499862).

Redirect damnation.miraheze.org to forsaken.wiki

---

redirects.yaml

Resolves [T14042](https://issue-tracker.miraheze.org/T14042).

T14042: Redirect fashiondreamer.miraheze.org to fashiondreamerwiki.miraheze.org
