miraheze/ssl

- redirects.yaml
We don't use wildcard certs for some Miraheze domains so we can enable the events.
> Enable event for some Miraheze domains

- redirects.yaml
It's not pointing at us thus does not work.
> Remove redirect for www.shkilev.online

- redirects.yaml
After recently having arrowversewiki deleted I am now having it redirected to dcmultiversewiki.
I will most likely have this redirect removed and the subdomain opened up again in a couple of months.
> Add arrowversewiki redirect to dcmultiversewiki

- certs.yaml
- redirects.yaml
I'm not sure where my other commit is, but I'll check after I push this. Should be no changes to the private keys and certificates needed as it's all using the `publictestwiki.com` certificate
**Edit:**  Second commit added. I guess I needed to create the PR first, _then_ add my second commit? Anyway, this can probably wait till @Reception123 is up, unless @paladox wants to review it and advise me of thing missing.
> Remove es.publictestwiki.com for deleted Spanish TestWiki

- .github/workflows/yamllint.yml
This would never be executed anyways, if the workflow is cancelled, then so is the notifications.
> Remove `cancelled` from IRC workflow notifications

- certs.yaml
Not needed as done on nenawiki.org
> disable events for ndg.nenawiki.org

- redirects.yaml
*.orain.org redirects to meta.miraheze.org, so this is unnecessary.
> Remove explicit meta.orain.org redirect

- redirects.yaml
This redirect is causing alerts in icinga since its a root redirect without using a cname.
> Remove thesimswiki.com redirect

- redirects.yaml
This won't actually work until test3 is decommissioned, but I don't think it'll do any harm either.
> Redirect test3 to betaheze

- redirects.yaml
This merge request contains an chnage in `redirects.yml` to redirect traffic from `recaptime.miraheze.org` to `wiki.recaptime.eu.org`, not necessarily for SEO reasons but to ensure people will not confused on the wiki URL, unless the `recaptime.eu.org` domain itself went dark or DNS stuff is broken.
> Add redirect for recaptimewiki's MH subdomain to its current custom domain

- redirects.yaml
* Should only be merged with miraheze/puppet#2641, at the same time.
> Move miraheze.wiki to the top of redirects.yaml

- certs.yaml
We already defined it in redirects.yaml. we cannot have it defined in two places.
> Remove wiki.rtapp.tk from certs.yaml

- certs.yaml
This is defined in redirects.yaml already and cannot be defined in two places.
> Remove wiki.recaptime.tk from certs.yaml

- redirects.yaml
Temporary until we cleanup instances in the databases (like GlobalNewFiles and ManageWiki settings)
> Redirect static-new.miraheze.org to static.miraheze.org

- redirects.yaml
It's conflicting with the name in certs.yaml.
> Fix projectpatternscom name in redirects.yaml

- redirects.yaml
Domain no longer points at miraheze.
> Don't redirect avid.miraheze.org

- redirects.yaml
We keep it disable for www.pyramidgames.wiki as we don't want it to trigger twice.
> Allow events for pyramidgames.wiki

- redirects.yaml
Resolve T12430 by imitating other `miraheze.org` to custom domain redirects. The domain `strinova.org` is managed by Cloudflare, so hopefully it doesn't make a difference in redirect configurations.
> T12430: Redirect strinova.miraheze.org to strinova.org

- certs.yaml
wiki.themanaworld.org is a domain routed via Cloudflare.
This is a test for whether or not Cloudflare will like mw* serving this certificate on a custom domain.
> Serve the miraheze.org wildcard on wiki.themanaworld.org

- redirects.yaml
Add redirect to bordrrevived.miraheze.org to fraudulentfrontera.miraheze.org. (due to wiki name change)
> Update redirects.yaml (add redirect)

- redirects.yaml
Add outlasterwiki and evicnoticewiki on redirects.yaml because the Miraheze.org domains are bugged, for some reason?
> Redirect outlasterwiki and evicnoticewiki to outlaster.peakprecision.wiki and evicnotice.peakprecision.wiki

- redirects.yaml
Not explicitly stated, but I'm guessing that's what they want since a CNAME for www.kingdomway.wiki is also set up
> T13707: Redirect www.kingdomway.wiki -> kingdomway.wiki

- certs.yaml
Partially resolves [T13844](https://issue-tracker.miraheze.org/T13884).
Possible follow-up needed on the Cloudflare side.
> T13844: Remove alternatewiki.tombricks.com from certs.yaml

- redirects.yaml
Resolves [T13926](https://issue-tracker.miraheze.org/T13926).
> T13926: Redirect backroomszh.miraheze.org to wiki.backroomszh.org

- certs.yaml
- redirects.yaml
Resolves [T13998](https://issue-tracker.miraheze.org/T13998).
> T13998: Remove 321nailswiki cert and redirect

- redirects.yaml
mariowiki moved to a different host. The other two wikis' domains expired.
> Remove expired domains from redirects
